version: 0.0
os: windows
files:
  - source: \monitor.py
    destination: C:\Script
hooks:
  BeforeInstall:
    - location: \before-install.bat
      timeout: 900
  AfterInstall:
    - location: \after-install.bat
      timeout: 900